# VoidTeams Configuration

# eliminar todos los equipos cuando el servidor se apaga/reinicia
clear-teams-on-stop: true

# Tamaño maximo de jugadores por equipo por defecto
max-team-size: 1

# Tipo de equipo por defecto (Choosen o Random)
team-type: "Choosen"

# Permitir a los jugadores usar el chat privado de su equipo (Usando /team chat)"
allow-team-chat: true

# true = usa los iconos de la lista (ej: ⚔, ★)
# false = usa un numeral aleatorio (ej: #1, #45, #99)
use-custom-icons: false

# Lista de iconos (solo se usa si use-custom-icons está en true)
team-icons:
  - "⚔"
  - "☠"
  - "★"
  - "UHC"